config/routes.rb
Rails.application.routes.draw do
  # get 'decision_categories/edit'

  get 'password_resets/new'

  get 'password_resets/edit'

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/status',  to: 'synchronization#index'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :participants,        only: [:index, :show, :create, :destroy]
  resources :decisions,           only: [:index, :show, :create, :destroy]
  resources :decision_categories
  resource  :synchronization, controller: 'synchronization'
end

app/models/decision_category.rb
class DecisionCategory < ApplicationRecord
  has_one :decision
  default_scope -> { order(:name) }
  validates :name, presence: true,
                   length: { maximum: 255 },
                   uniqueness: { case_sensitive: false }

  def to_s
    name
  end

end

app/controllers/decision_categories_controller.rb
class DecisionCategoriesController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  before_action :logged_in_user, only: [:index, :destroy]
  before_action :admin_user,     only: :destroy

  def index
    @decision_categories = DecisionCategory.all.paginate(page: params[:page])
  end

  def show
  end

  def edit
    @decision_category = DecisionCategory.find(params[:id])
  end

  def update
    @decision_category = DecisionCategory.find(params[:id])
    if @decision_category.update_attributes(decision_category_params)
      flash[:success] = "Category updated"
      redirect_to decision_categories_url
    else
      render 'edit'
    end
  end


  private


  def decision_category_params
    params.require(:decision_category).permit(:name)
  end

end

app/helpers/decision_categories_helper.rb
module DecisionCategoriesHelper
end

app/views/decision_categories/_decision_category.html.erb
<li>
  <%= decision_category.name %>
  <% if current_user.admin? %>
    | <%= link_to "edit", edit_decision_category_path(decision_category) %>
    | <%= link_to "delete", decision_category, method: :delete,
                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/decision_categories/edit.html.erb
<% provide(:title, 'Edit decision category') %>
<h1>Update decision category name</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@decision_category, url: decision_category_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/decision_categories/index.html.erb
<% provide(:title, 'All decision categories') %>
<h1><%= yield(:title) %></h1>
<!--All decision categories-->

<%= will_paginate(@decision_categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, :class => 'pagination-sm') %>

<ul class="decision_categories">
  <%= render @decision_categories %>
</ul>

<%= will_paginate(@decision_categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, :class => 'pagination-sm') %>