config/routes.rb
Rails.application.routes.draw do
  # get 'decision_categories/edit'

  get 'password_resets/new'

  get 'password_resets/edit'

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/status',  to: 'synchronization#index'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :participants,        only: [:index, :show, :create, :destroy]
  resources :decisions,           only: [:index, :show, :create, :destroy]
  resources :decision_categories
  resource  :synchronization, controller: 'synchronization'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The ÚOHS Application by Lukáš Lipinský
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <%= link_to "ÚOHS app", root_path, id: "logo", class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav ml-auto">
      <li class="nav-item <%= active_for(controller: 'static_pages', action: 'home') %>"><%= link_to "Home", root_path, class: 'nav-link' %></li>
      <li class="nav-item <%= active_for(controller: 'static_pages', action: 'help') %>"><%= link_to "Help", help_path, class: 'nav-link' %></li>
      <% if logged_in? %>
        <li class="nav-item <%= active_for(controller: 'users', action: 'index') %>"><%= link_to "Users", users_path, class: 'nav-link' %></li>
        <% if current_user.admin? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Database <b class="caret"></b>
            </a>
            <div class="dropdown-menu">
              <%= link_to "Participants", participants_path , class: 'dropdown-item' %>
              <%= link_to "Decisions", decisions_path, class: 'dropdown-item' %>
              <%= link_to "Decision categories", decision_categories_path, class: 'dropdown-item' %>
              <%= link_to "Status", status_path, class: 'dropdown-item' %>
            </div>
        <% end %>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account <b class="caret"></b>
          </a>
          <div class="dropdown-menu">
            <%= link_to "Profile", current_user, class: 'dropdown-item' %>
            <%= link_to "Settings", edit_user_path(current_user), class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", logout_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li><%= link_to "Log in", login_path, class: 'nav-link' %></li>
      <% end %>

    </ul>

  </div>

</nav>

app/views/layouts/_progressbar.html.erb
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" id="progress-bar" style="width:<%= Redis.current.get(:current_progress) %>%">
  </div>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/progressbar' if redis(get: :in_progress) == "true" %>
    <div class="container<%= yield(:fluid) == 'true' ? '-fluid' : '' %>">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>